# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#  
#       1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#  
# Find the sum of all the even-valued terms in the sequence which do not
# exceed one million.

evens = []
a, b = 1, 2
while true
  break if (a+b) > 1000000
  evens.push(a+b) if (a+b)%2 == 0
  a, b = b, a+b
end

print evens.inject(0) { |sum, n| sum += n } + 2
